# Generated by Django 6.0.6 on 2026-06-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '__first__'),
        ('resources', '0002_resource_subject_resource_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='academics.subject'),
        ),
    ]
