# Generated by Django 6.0.6 on 2026-06-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_year_alter_resource_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='youtube_link',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='youtube_url',
        ),
    ]
